name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{steps.backend-tests.outputs.report}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
      
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Execute backend unit tests
        id: backend-tests
        working-directory: ./bugtracker-backend

        run: |
          
          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt

          echo "Go tests coverage report" >> ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}
          cat coverage.txt >> ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}
          
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


          go test -v ./... | go-junit-report > test-results.xml


      - name: publish backend test results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Backend units tests report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit

  unit-tests-frontend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{steps.frontend-tests.outputs.report}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: bugtracker-frontend/package-lock.json
      
      - name: execute frontend unit tests
        id: frontend-tests
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full_output.txt 

          echo "Frontend Unit Tests Summary" >> ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}
          cat full_output.txt >> ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}

          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat full_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: publish frontend test results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Frontend Unit Tests report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit


  create-coverage-comment:
    if: github.event_name == 'pull_request' 
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Create backend coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with: 
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Backend tests coverage report:
            ```
            ${{ needs.unit-tests-backend.outputs.coverage }}
            ```

      - name: Create frontend coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with: 
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Frontend tests results:
            ```
            ${{ needs.unit-tests-frontend.outputs.coverage }}
            ```

  api-e2e-perf-tests:
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Launch Application
        run: |
          docker compose up --build -d
          npx wait-port http://localhost:8080/api/health -t 30000
    
      - name: Run API tests
        working-directory: ./tests-api
        env:
          CI: "1"
        run: |
          npm ci
          npx playwright test

      - name: Run E2E tests
        working-directory: ./tests-e2e
        run: |
          npm ci
          npx playwright install
          npx playwright test

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        
      - name: Run Performance tests
        uses: grafana/run-k6-action@v1
        with:
          path: ./tests-perf/script.js
          flags: --out json=summary.json 

      - name: Shutdown Application
        run: docker compose down

      - name: upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Test Results
          path: ./tests-e2e/test-results/
          retention-days: 30
      
      - name: upload E2E playwright results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E playwright Test Results
          path: ./tests-e2e/playwright-report/
          retention-days: 30    


      - name: upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API Test Results
          path: ./tests-api/test-results/
          retention-days: 30
        
      - name: upload API test playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API playwright report
          path: ./tests-api/playwright-report/
          retention-days: 30
          

      - name: Publish API test results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: API Tests Report
          path: tests-api/test-results/*.xml
          reporter: jest-junit 

      - name: Publish E2E playwright results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: API Tests Report
          path: tests-e2e/test-results/results.xml
          reporter: jest-junit 